######################################################################
# Automatically generated by qmake (3.0) Fri Mar 13 20:39:33 2015
######################################################################

TEMPLATE             = app
TARGET               = test
CONFIG              += c++11
INCLUDEPATH         += . hpp TestCases ../inc
DEFINES             += __TESTING__
# General libs
unix:LIBS           += -lpthread -lboost_system -lboost_serialization -lboost_random

# Input
HEADERS += manifest.hpp \
           hpp/bootstrap.hpp \
           hpp/registery.hpp \
           hpp/testCase.hpp \
           hpp/teststrap.hpp \
           TestCases/chromosomeTestCase.hpp \
           TestCases/populationTestCase.hpp \
    TestCases/populationTestCase.hpp \
    TestCases/dataTestCase.hpp \
    TestCases/gaConfigTestCase.hpp
SOURCES += testerMain.cpp cpp/registery.cpp cpp/testCase.cpp ../src/population.cpp
