function script
    clear, clc, close all;

    imdb = getImdb('data/jaffe');

    opts.train.batchSize = 40;
    opts.train.numEpochs = 100;
    opts.train.learningRate = 1e-3;

    for i = 1:5
        fprintf('Building network configuration for iteration# %i...', i);
        f = 1e-2;
        net.layers = {};
        net.layers{end+1} = struct('type', 'conv', ...
                                   'weights', {{f*randn(5,5,1,50, 'single'), zeros(1, 50, 'single')}}, ...
                                   'stride', 1, ...
                                   'pad', 0);
        net.layers{end+1} = struct('type', 'pool', ...
                                   'method', 'max', ...
                                   'pool', [2 2], ...
                                   'stride', 2, ...
                                   'pad', 0);
        net.layers{end+1} = struct('type', 'conv', ...
                                   'weights', {{f*randn(5,5,50,100, 'single'),zeros(1,100,'single')}}, ...
                                   'stride', 1, ...
                                   'pad', 0);
        net.layers{end+1} = struct('type', 'pool', ...
                                   'method', 'max', ...
                                   'pool', [2 2], ...
                                   'stride', 2, ...
                                   'pad', 0);
        net.layers{end+1} = struct('type', 'conv', ...
                                   'weights', {{f*randn(4,4,100,6, 'single'), zeros(1,6,'single')}}, ...
                                   'stride', 1, ...
                                   'pad', 0);
        net.layers{end+1} = struct('type', 'softmaxloss');

        fprintf('[Done]\n');

        [net, info] = cnn_train(net, imdb, @getBatch, ...
            opts.train, ...
            'val', find(imdb.images.set == 3));

        target_folder = sprintf('data/exec/%i', i);
        fprintf('Moving result files into `%s`', target_folder);
        if exist(target_folder, 'dir'), rmdir(target_folder, 's'); end
        mkdir(target_folder);
        movefile('data/exp/net-train.pdf', target_folder);
        movefile(sprintf('data/exp/net-epoch-%i.mat', opts.train.numEpochs), target_folder);
        save(sprintf('%s/imdb.mat', target_folder), 'imdb');
        fprintf('[DONE]\n');
    end

function [im, labels] = getBatch(imdb, batch)
    im = imdb.images.data(:,:,:,batch);
    labels = imdb.images.labels(batch, 1);