######################################################################
# Automatically generated by qmake (3.0) Thu Jul 2 19:57:52 2015
######################################################################

TEMPLATE = app
TARGET = ESPP
CONFIG += c++11
INCLUDEPATH += . inc
LIBS = -lpthread
DEFINES += QTCREATOR

# Input
SOURCES += main.cpp \
    src/eStrategy.cpp

HEADERS += \
    inc/stdafx.hpp \
    inc/config.hpp \
    inc/eStrategy.hpp \
    inc/chromosome.hpp \
    inc/random.hpp
